"""
Data masking, anonymization, and exclusion pipeline for MemoryStore.

Plugs into MemoryStore.set_redaction_hook() — applied at read time,
never stored to DB.

Three strategies:
- MASK: replace field value with "*****"
- ANONYMIZE: replace with deterministic pseudonym "<Tamagochi>" via HMAC
- REDACT: remove field entirely from value dict
"""

from __future__ import annotations

import hashlib
import hmac
from dataclasses import dataclass
from enum import Enum
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from cemaf.memory.base import MemoryItem, RedactionHook


# ---------------------------------------------------------------------------
# 1024-entry pseudonym corpus
# Generated by combining prefix stems with suffix endings to produce
# 1024 distinct fantasy/unique name entries.
# ---------------------------------------------------------------------------
_PREFIX_STEMS = (
    "Ag", "Al", "Am", "An", "Ar", "As", "At", "Az",
    "Ba", "Be", "Bi", "Bo", "Br", "Bu", "By", "Ca",
    "Ce", "Ch", "Ci", "Cl", "Co", "Cr", "Cu", "Cy",
    "Da", "De", "Di", "Do", "Dr", "Du", "Dy", "El",
)

_SUFFIX_ENDINGS = (
    "ael", "ain", "alis", "alos", "alur", "amis", "anor", "anus",
    "aros", "arth", "atus", "axen", "axor", "azel", "azis", "azor",
    "chen", "chor", "cius", "cion", "cira", "cith", "civr", "clar",
    "clis", "clor", "clyx", "coar", "coel", "coin", "coix", "corb",
)

_DEFAULT_CORPUS: tuple[str, ...] = tuple(
    p + s for p in _PREFIX_STEMS for s in _SUFFIX_ENDINGS
)
assert len(_DEFAULT_CORPUS) == 1024, f"corpus size {len(_DEFAULT_CORPUS)} != 1024"


# ---------------------------------------------------------------------------
# Strategy enum
# ---------------------------------------------------------------------------

class MaskingStrategy(str, Enum):
    """How to transform a matched field value."""

    MASK = "mask"
    ANONYMIZE = "anonymize"
    REDACT = "redact"


# ---------------------------------------------------------------------------
# MaskingRule — one field + one strategy
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class MaskingRule:
    """Declares how a single field in MemoryItem.value should be transformed."""

    field: str
    strategy: MaskingStrategy


# ---------------------------------------------------------------------------
# PseudonymVault — deterministic, non-reversible pseudonyms via HMAC
# ---------------------------------------------------------------------------

class PseudonymVault:
    """
    Maps real string values to deterministic pseudonyms via HMAC-SHA256.

    The pseudonym is derived from HMAC-SHA256(secret_key, real_value),
    using the first 8 bytes of the digest as an index into the corpus.
    Reverse lookup is intentionally impossible without the secret_key —
    even knowing the corpus and all pseudonyms does not reveal the originals.

    Args:
        secret_key: Raw bytes used as the HMAC key.  Keep this secret.
        corpus: Optional list of display names.  Defaults to the built-in
                1024-entry fantasy corpus (_DEFAULT_CORPUS).
    """

    def __init__(self, secret_key: bytes, corpus: list[str] | None = None) -> None:
        self._key = secret_key
        self._corpus: tuple[str, ...] = tuple(corpus) if corpus is not None else _DEFAULT_CORPUS
        if not self._corpus:
            raise ValueError("PseudonymVault corpus must not be empty")

    def pseudonymize(self, real_value: str) -> str:
        """
        Return a deterministic pseudonym for *real_value*.

        Steps:
        1. Compute HMAC-SHA256(secret_key, real_value.encode("utf-8")).
        2. Take the first 8 bytes of the digest as a little-endian uint64.
        3. Index into the corpus with modulo to get the display name.
        4. Return ``f"<{name}>"``.

        The same (key, real_value) pair always produces the same pseudonym.
        Different keys produce different pseudonyms for the same real_value.
        """
        digest = hmac.new(self._key, real_value.encode("utf-8"), hashlib.sha256).digest()
        idx = int.from_bytes(digest[:8], "little") % len(self._corpus)
        return f"<{self._corpus[idx]}>"


# ---------------------------------------------------------------------------
# MaskingPipeline — applies ordered rules to a MemoryItem
# ---------------------------------------------------------------------------

class MaskingPipeline:
    """
    Apply an ordered list of MaskingRules to MemoryItem.value at read time.

    Rules are applied left-to-right.  Fields absent from MemoryItem.value
    are silently skipped.  Fields not referenced by any rule are unchanged.
    """

    def __init__(
        self,
        rules: list[MaskingRule],
        vault: PseudonymVault | None = None,
    ) -> None:
        self._rules = list(rules)
        self._vault = vault

    def apply(self, item: "MemoryItem") -> "MemoryItem":
        """Return a new MemoryItem with transformed values per the rules."""
        # Import here to avoid module-level circular during TYPE_CHECKING
        new_value: dict[str, Any] = dict(item.value)

        for rule in self._rules:
            if rule.field not in new_value:
                continue

            match rule.strategy:
                case MaskingStrategy.MASK:
                    new_value[rule.field] = "*****"
                case MaskingStrategy.ANONYMIZE:
                    if self._vault is None:
                        raise RuntimeError(
                            "MaskingStrategy.ANONYMIZE requires a PseudonymVault; "
                            "pass vault= to MaskingPipeline.__init__"
                        )
                    raw = str(new_value[rule.field])
                    new_value[rule.field] = self._vault.pseudonymize(raw)
                case MaskingStrategy.REDACT:
                    del new_value[rule.field]

        return item.with_update(new_value)


# ---------------------------------------------------------------------------
# Factory helper
# ---------------------------------------------------------------------------

def create_masking_hook(pipeline: MaskingPipeline) -> "RedactionHook":
    """
    Wrap *pipeline* as a RedactionHook compatible with
    ``MemoryStore.set_redaction_hook()``.

    The returned callable receives a MemoryItem and returns a redacted copy.
    It is safe to set as a redaction hook on any MemoryStore implementation.

    Example::

        hook = create_masking_hook(pipeline)
        store.set_redaction_hook(hook)
    """
    def _hook(item: "MemoryItem") -> "MemoryItem":
        return pipeline.apply(item)

    return _hook


# ---------------------------------------------------------------------------
# ExclusionFilter — post-filter helper for list_by_scope()
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ExclusionFilter:
    """
    Determines whether a MemoryItem should be **excluded** from results.

    This is a post-filter companion for MemoryStore.list_by_scope() when
    the underlying store does not natively support server-side filtering
    (e.g., InMemoryStore).  PostgresMemoryStore accepts SQL-level filters
    directly.

    An item **matches** (should be excluded) when ``item.value.get(field)``
    is contained in ``excluded_values``.

    Example::

        f = ExclusionFilter(field="status", excluded_values=("deleted", "archived"))
        active_items = [i for i in items if not f.matches(i)]
    """

    field: str
    excluded_values: tuple[Any, ...]

    def matches(self, item: "MemoryItem") -> bool:
        """Return True if *item* should be excluded (i.e. its field value is disallowed)."""
        return item.value.get(self.field) in self.excluded_values
