"""MetaScaffolder — assembles generated specs + agents into a runnable CEMAF-based app."""

from __future__ import annotations

import asyncio
import json
import keyword
import logging
import shutil
import sys
from collections.abc import Mapping
from pathlib import Path

from cemaf.agents.base import Agent, AgentContext, AgentResult, AgentState
from cemaf.core.types import AgentID
from cemaf.meta.goals import (
    GeneratedAgent,
    ProjectSkeleton,
    ScaffoldGoal,
    ScaffoldResult,
)

logger = logging.getLogger(__name__)

_CEMAF_SOURCE_PLACEHOLDER = (
    "# FIXME: set cemaf_source on ScaffoldGoal to a resolvable spec "
    '(e.g. "cemaf @ git+https://...@<sha>" or "cemaf @ file:///path/to/cemaf"). '
    "The default below is not resolvable by uv."
)


def render_project(*, skeleton: ProjectSkeleton) -> Mapping[str, str]:
    """Render a ProjectSkeleton to the file map a MetaScaffolder should write.

    Pure function — no I/O, no clock reads, no randomness. Same input
    produces byte-equal output.
    """
    files: dict[str, str] = {
        "pyproject.toml": _render_pyproject(skeleton=skeleton),
        "README.md": _render_readme(skeleton=skeleton),
        f"src/{skeleton.module_name}/__init__.py": _render_init(skeleton=skeleton),
        f"src/{skeleton.module_name}/agents.py": _render_agents(skeleton=skeleton),
        f"src/{skeleton.module_name}/dags.py": _render_dags(skeleton=skeleton),
        f"src/{skeleton.module_name}/bootstrap.py": _render_bootstrap(skeleton=skeleton),
        "tests/__init__.py": "",
        "tests/test_smoke.py": _render_smoke_test(skeleton=skeleton),
    }
    return files


def _toml_string(value: str) -> str:
    """Escape a value for use inside a TOML basic string.

    TOML basic strings use the same escape rules as JSON strings. Using
    `json.dumps` gives us correct handling of `"`, `\\`, newlines, and
    non-printable characters without rolling our own escape table.
    """
    return json.dumps(value, ensure_ascii=False)


def _py_string(value: str) -> str:
    """Escape a value for use as a Python string literal (same rules as JSON)."""
    return json.dumps(value, ensure_ascii=False)


def _render_pyproject(*, skeleton: ProjectSkeleton) -> str:
    name_literal = _toml_string(skeleton.module_name)
    desc_literal = _toml_string(skeleton.description)
    cemaf_dep_literal = (
        _toml_string(skeleton.cemaf_source) if skeleton.cemaf_source else _toml_string("cemaf")
    )
    preamble = "" if skeleton.cemaf_source else f"\n{_CEMAF_SOURCE_PLACEHOLDER}\n"
    packages_literal = _toml_string(f"src/{skeleton.module_name}")
    return f"""{preamble}[project]
name = {name_literal}
version = "0.1.0"
description = {desc_literal}
requires-python = ">=3.13"
dependencies = [
    {cemaf_dep_literal},
    "pydantic>=2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [{packages_literal}]
"""


def _render_readme(*, skeleton: ProjectSkeleton) -> str:
    # Title and description go directly into markdown where quotes are safe.
    return f"""# {skeleton.title}

{skeleton.description}

Generated by CEMAF MetaScaffolder from an OpenSpec proposal.

## Quickstart

```python
from {skeleton.module_name}.bootstrap import create_app_executor

executor = create_app_executor()
```
"""


def _render_init(*, skeleton: ProjectSkeleton) -> str:
    return f'"""Entry point for the {skeleton.module_name} package."""\n'


def _render_agents(*, skeleton: ProjectSkeleton) -> str:
    if not skeleton.generated_agents:
        return (
            '"""Generated agents for this app."""\n'
            "\n"
            "# No agents were synthesized; register your own in bootstrap.py.\n"
        )
    header = '"""Generated agents — produced by MetaSynthesizer."""\n\n'
    return header + "\n\n".join(a.source.rstrip() for a in skeleton.generated_agents) + "\n"


def _render_dags(*, skeleton: ProjectSkeleton) -> str:
    # Description goes into a DAG kwarg — must be a valid Python string literal.
    dag_name_literal = _py_string(f"{skeleton.module_name}_main")
    desc_literal = _py_string(skeleton.description)
    return f'''"""DAG factories for {skeleton.module_name}."""

from cemaf.orchestration.dag import DAG


def create_main_dag() -> DAG:
    """Default DAG — extend as your app grows."""
    return DAG(name={dag_name_literal}, description={desc_literal})
'''


def _render_bootstrap(*, skeleton: ProjectSkeleton) -> str:
    agents = skeleton.generated_agents
    if agents:
        import_names = ", ".join(sorted({a.class_name for a in agents} | {a.goal_class_name for a in agents}))
        agent_imports = f"from {skeleton.module_name}.agents import {import_names}\n"
        registrations = "\n".join(
            f"    registry.register_agent(agent_instance={a.class_name}(), goal_type={a.goal_class_name})"
            for a in agents
        )
    else:
        agent_imports = "# No agents to import — add them here as your app grows.\n"
        registrations = "    # no agents registered"

    return f'''"""App bootstrap — wires the registry and returns a DAGExecutor."""

from cemaf.agents.registry import AgentRegistry
from cemaf.bootstrap import create_executor
from cemaf.orchestration.executor import DAGExecutor, ExecutorConfig
from cemaf.orchestration.services import RuntimeServices

{agent_imports}

def create_app_registry() -> AgentRegistry:
    """Register this app's agents and return the registry."""
    registry = AgentRegistry()
{registrations}
    return registry


def create_app_executor(
    *,
    services: RuntimeServices | None = None,
    config: ExecutorConfig | None = None,
) -> DAGExecutor:
    """Build a DAGExecutor for this app."""
    return create_executor(
        agent_registry=create_app_registry(),
        services=services,
        config=config,
    )
'''


def _render_smoke_test(*, skeleton: ProjectSkeleton) -> str:
    expected_name_literal = _py_string(f"{skeleton.module_name}_main")
    return f'''"""Smoke test — imports and wires the app."""

from {skeleton.module_name}.bootstrap import create_app_executor, create_app_registry
from {skeleton.module_name}.dags import create_main_dag


def test_registry_builds() -> None:
    registry = create_app_registry()
    assert registry is not None


def test_executor_builds() -> None:
    executor = create_app_executor()
    assert executor is not None


def test_main_dag_is_valid() -> None:
    dag = create_main_dag()
    assert dag.name == {expected_name_literal}
'''


# stdlib modules we refuse to shadow — keeps generated apps from clobbering
# common imports in their own namespace.
_FORBIDDEN_PROJECT_NAMES = frozenset(sys.stdlib_module_names) | frozenset({"cemaf", "pydantic", "pytest"})


class MetaScaffolder(Agent[ScaffoldGoal, ScaffoldResult]):
    """Write a runnable CEMAF-based app to disk from a ProposalDoc + synthesized agents."""

    def __init__(self) -> None:
        self._locks: dict[str, asyncio.Lock] = {}
        self._registry_lock = asyncio.Lock()

    @property
    def id(self) -> AgentID:
        return AgentID("MetaScaffolder")

    @property
    def description(self) -> str:
        return "Assembles generated specs and agents into a runnable CEMAF-based app on disk."

    @property
    def skills(self) -> tuple[()]:
        return ()

    async def run(
        self,
        goal: ScaffoldGoal,
        context: AgentContext,
    ) -> AgentResult[ScaffoldResult]:
        state = AgentState()
        try:
            _validate_module_name(name=goal.project_name)
            target_dir = Path(goal.target_dir).resolve()
            project_root = (target_dir / goal.project_name).resolve()
            _validate_within(target=project_root, root=target_dir)
            lock = await self._acquire_project_lock(project_root=project_root)
            async with lock:
                await self._prepare_root(project_root=project_root, overwrite=goal.overwrite)

                skeleton = ProjectSkeleton(
                    project_name=goal.project_name,
                    module_name=goal.project_name,
                    title=goal.proposal.title,
                    description=_first_nonempty_line(text=goal.proposal.why)[:200],
                    generated_agents=goal.generated_agents,
                    cemaf_source=goal.cemaf_source,
                )
                files = render_project(skeleton=skeleton)
                written = await asyncio.to_thread(_write_files, project_root, files)

            result = ScaffoldResult(
                project_root=str(project_root),
                module_name=skeleton.module_name,
                written_files=tuple(sorted(written)),
            )
            return AgentResult.ok(output=result, state=state)
        except asyncio.CancelledError:
            raise
        except (ValueError, OSError) as exc:
            logger.exception("[MetaScaffolder] failed")
            return AgentResult.fail(error=str(exc), state=state)

    async def _acquire_project_lock(self, *, project_root: Path) -> asyncio.Lock:
        """Per-project-root asyncio.Lock — serializes concurrent scaffolds to the same target."""
        key = str(project_root)
        async with self._registry_lock:
            return self._locks.setdefault(key, asyncio.Lock())

    async def _prepare_root(self, *, project_root: Path, overwrite: bool) -> None:
        if project_root.exists():
            has_entries = any(project_root.iterdir())
            if has_entries and not overwrite:
                raise ValueError(
                    f"Project directory {project_root} already exists and is non-empty; "
                    "pass overwrite=True to replace it"
                )
            if has_entries and overwrite:
                await asyncio.to_thread(shutil.rmtree, project_root)
        project_root.mkdir(parents=True, exist_ok=True)


def _first_nonempty_line(*, text: str) -> str:
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped
    return text.strip() or "CEMAF-based app"


def _validate_module_name(*, name: str) -> None:
    if not name.isidentifier():
        raise ValueError(f"project_name {name!r} is not a valid Python identifier")
    if keyword.iskeyword(name) or keyword.issoftkeyword(name):
        raise ValueError(f"project_name {name!r} is a reserved Python keyword")
    if name in _FORBIDDEN_PROJECT_NAMES:
        raise ValueError(
            f"project_name {name!r} collides with a stdlib or known package name; "
            "pick a project-specific name"
        )


def _validate_within(*, target: Path, root: Path) -> None:
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"Refusing to write outside target_dir: {target}") from exc


def _write_files(root: Path, files: Mapping[str, str]) -> list[str]:
    written: list[str] = []
    for rel_path, content in files.items():
        if ".." in Path(rel_path).parts:
            raise ValueError(f"Refusing to write outside project root: {rel_path}")
        target = root / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(rel_path)
    return written


__all__ = [
    "MetaScaffolder",
    "render_project",
    "GeneratedAgent",
]
