"""MetaScaffolder — assembles generated specs + agents into a runnable CEMAF-based app."""

from __future__ import annotations

import asyncio
import keyword
import logging
import shutil
from collections.abc import Mapping
from pathlib import Path

from cemaf.agents.base import Agent, AgentContext, AgentResult, AgentState
from cemaf.core.types import AgentID
from cemaf.meta.goals import (
    ProjectSkeleton,
    ScaffoldGoal,
    ScaffoldResult,
)

logger = logging.getLogger(__name__)


def render_project(*, skeleton: ProjectSkeleton) -> Mapping[str, str]:
    """Render a ProjectSkeleton to the file map a MetaScaffolder should write.

    Pure function — no I/O, no clock reads, no randomness. Same input
    produces byte-equal output.
    """
    files: dict[str, str] = {
        "pyproject.toml": _render_pyproject(skeleton=skeleton),
        "README.md": _render_readme(skeleton=skeleton),
        f"src/{skeleton.module_name}/__init__.py": _render_init(skeleton=skeleton),
        f"src/{skeleton.module_name}/agents.py": _render_agents(skeleton=skeleton),
        f"src/{skeleton.module_name}/dags.py": _render_dags(skeleton=skeleton),
        f"src/{skeleton.module_name}/bootstrap.py": _render_bootstrap(skeleton=skeleton),
        "tests/__init__.py": "",
        "tests/test_smoke.py": _render_smoke_test(skeleton=skeleton),
    }
    return files


def _render_pyproject(*, skeleton: ProjectSkeleton) -> str:
    return f"""[project]
name = "{skeleton.module_name}"
version = "0.1.0"
description = "{skeleton.description}"
requires-python = ">=3.13"
dependencies = [
    "cemaf",
    "pydantic>=2.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{skeleton.module_name}"]
"""


def _render_readme(*, skeleton: ProjectSkeleton) -> str:
    return f"""# {skeleton.title}

{skeleton.description}

Generated by CEMAF MetaScaffolder from an OpenSpec proposal.

## Quickstart

```python
from {skeleton.module_name}.bootstrap import create_app_executor

executor = create_app_executor()
```
"""


def _render_init(*, skeleton: ProjectSkeleton) -> str:
    return f'"""Entry point for the {skeleton.module_name} package."""\n'


def _render_agents(*, skeleton: ProjectSkeleton) -> str:
    if not skeleton.agent_sources:
        return (
            '"""Generated agents for this app."""\n'
            "\n"
            "# No agents were synthesized; add your own by registering them in bootstrap.py.\n"
        )
    header = '"""Generated agents — produced by MetaSynthesizer."""\n\n'
    return header + "\n\n".join(src.rstrip() for src in skeleton.agent_sources) + "\n"


def _render_dags(*, skeleton: ProjectSkeleton) -> str:
    return f'''"""DAG factories for {skeleton.module_name}."""

from cemaf.core.types import NodeID
from cemaf.orchestration.dag import DAG, Edge, Node


def create_main_dag() -> DAG:
    """Default DAG — extend as your app grows."""
    dag = DAG(name="{skeleton.module_name}_main", description="{skeleton.description}")
    return dag
'''


def _render_bootstrap(*, skeleton: ProjectSkeleton) -> str:
    registrations = "\n".join(
        f"    registry.register_agent(agent_instance={cls}(), goal_type={cls}Goal)"
        for cls in skeleton.agent_class_names
    )
    agent_imports = (
        f"from {skeleton.module_name}.agents import (\n"
        + "\n".join(f"    {cls}," for cls in skeleton.agent_class_names)
        + "\n)\n"
        if skeleton.agent_class_names
        else "# No agents to import — add them here as your app grows.\n"
    )
    return f'''"""App bootstrap — wires the registry and returns a DAGExecutor."""

from cemaf.agents.registry import AgentRegistry
from cemaf.bootstrap import create_executor
from cemaf.orchestration.executor import DAGExecutor, ExecutorConfig
from cemaf.orchestration.services import RuntimeServices

{agent_imports}

def create_app_registry() -> AgentRegistry:
    """Register this app's agents and return the registry."""
    registry = AgentRegistry()
{registrations or "    # no agents registered"}
    return registry


def create_app_executor(
    *,
    services: RuntimeServices | None = None,
    config: ExecutorConfig | None = None,
) -> DAGExecutor:
    """Build a DAGExecutor for this app."""
    return create_executor(
        agent_registry=create_app_registry(),
        services=services,
        config=config,
    )
'''


def _render_smoke_test(*, skeleton: ProjectSkeleton) -> str:
    return f'''"""Smoke test — imports and wires the app."""

from {skeleton.module_name}.bootstrap import create_app_executor, create_app_registry
from {skeleton.module_name}.dags import create_main_dag


def test_registry_builds() -> None:
    registry = create_app_registry()
    assert registry is not None


def test_executor_builds() -> None:
    executor = create_app_executor()
    assert executor is not None


def test_main_dag_is_valid() -> None:
    dag = create_main_dag()
    assert dag.name == "{skeleton.module_name}_main"
'''


class MetaScaffolder(Agent[ScaffoldGoal, ScaffoldResult]):
    """Write a runnable CEMAF-based app to disk from a ProposalDoc + synthesized agents."""

    @property
    def id(self) -> AgentID:
        return AgentID("MetaScaffolder")

    @property
    def description(self) -> str:
        return "Assembles generated specs and agents into a runnable CEMAF-based app on disk."

    @property
    def skills(self) -> tuple[()]:
        return ()

    async def run(
        self,
        goal: ScaffoldGoal,
        context: AgentContext,
    ) -> AgentResult[ScaffoldResult]:
        state = AgentState()
        try:
            _validate_module_name(name=goal.project_name)
            target_dir = Path(goal.target_dir).resolve()
            project_root = (target_dir / goal.project_name).resolve()
            _validate_within(target=project_root, root=target_dir)
            await self._prepare_root(project_root=project_root, overwrite=goal.overwrite)

            skeleton = ProjectSkeleton(
                project_name=goal.project_name,
                module_name=goal.project_name,
                title=goal.proposal.title,
                description=goal.proposal.why.splitlines()[0][:200],
                agent_sources=goal.generated_agents,
                agent_class_names=goal.agent_class_names,
            )
            files = render_project(skeleton=skeleton)
            written = await asyncio.to_thread(_write_files, project_root, files)

            result = ScaffoldResult(
                project_root=str(project_root),
                module_name=skeleton.module_name,
                written_files=tuple(sorted(written)),
            )
            return AgentResult.ok(output=result, state=state)
        except asyncio.CancelledError:
            raise
        except (ValueError, OSError) as exc:
            logger.exception("[MetaScaffolder] failed")
            return AgentResult.fail(error=str(exc), state=state)

    async def _prepare_root(self, *, project_root: Path, overwrite: bool) -> None:
        if project_root.exists():
            has_entries = any(project_root.iterdir())
            if has_entries and not overwrite:
                raise ValueError(
                    f"Project directory {project_root} already exists and is non-empty; "
                    "pass overwrite=True to replace it"
                )
            if has_entries and overwrite:
                await asyncio.to_thread(shutil.rmtree, project_root)
        project_root.mkdir(parents=True, exist_ok=True)


def _validate_module_name(*, name: str) -> None:
    if not name.isidentifier():
        raise ValueError(f"project_name {name!r} is not a valid Python identifier")
    if keyword.iskeyword(name) or keyword.issoftkeyword(name):
        raise ValueError(f"project_name {name!r} is a reserved Python keyword")


def _validate_within(*, target: Path, root: Path) -> None:
    try:
        target.relative_to(root)
    except ValueError as exc:
        raise ValueError(f"Refusing to write outside target_dir: {target}") from exc


def _write_files(root: Path, files: Mapping[str, str]) -> list[str]:
    written: list[str] = []
    for rel_path, content in files.items():
        if ".." in Path(rel_path).parts:
            raise ValueError(f"Refusing to write outside project root: {rel_path}")
        target = root / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        written.append(rel_path)
    return written


__all__ = [
    "MetaScaffolder",
    "render_project",
]
